import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterOutlet } from '@angular/router';
import { InputDirective } from './CustomDirectives/input-rule';
import { RequiredError } from './CustomDirectives/required-error';

type KycStatus = 'Pending' | 'Verified';

interface KycApplication {
  id: number; // unique identifier (simulating backend-generated ID)
  fullName: string; // applicant full name
  mobile: string; // 10-digit mobile number
  pan: string; // 10-character PAN
  email: string; // applicant email id
  status: KycStatus; // current processing status
}

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, FormsModule, RequiredError, InputDirective],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App {
  // FORM MODEL (Template-driven form values)
  // These are bound to the input fields using [(ngModel)].
  // They always contain the latest values typed by the user.
  fullName = '';
  mobile = '';
  pan = '';
  email = '';

  // UI STATE (Controls when validation errors are shown)
  // We keep it false initially so the form looks clean on first load.
  // We set it true only when user clicks Submit.
  // Template uses this to show:
  // - validation messages
  // - RequiredErrorDirective styling
  isSubmitted = false;

  // IN-MEMORY STORAGE (Demo Purpose)
  // In real applications, IDs are generated by the backend database.
  // Here we simulate that using an auto-increment variable.
  private nextId = 1001;

  // Stores all submitted applications in memory.
  // This list is shown in the dashboard on the right side.
  applications: KycApplication[] = [];

  get isFullNameInvalid(): boolean {
    return this.fullName.trim() === '';
  }

  //get is used to create read-only methods that can be used in the template like properties.
  get isMobileInvalid(): boolean {
    return this.mobile.length !== 10;
  }

  get isPanInvalid(): boolean {
    return this.pan.length !== 10;
  }

  get isEmailInvalid(): boolean {
    return !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.email.trim());
  }

  get isFormInvalid(): boolean {
    return (
      this.isFullNameInvalid || this.isMobileInvalid || this.isPanInvalid || this.isEmailInvalid
    );
  }

  submit(): void {
    this.isSubmitted = true;

    if (this.isFormInvalid) return;

    const newApp: KycApplication = {
      id: this.nextId++, // simulate auto-generated unique ID
      fullName: this.fullName.trim(), // clean full name
      mobile: this.mobile.trim(), // clean mobile
      pan: this.pan.trim(), // clean PAN
      email: this.email.trim(), // clean email
      status: 'Pending', // default status for newly created record
    };

    this.applications = [newApp, ...this.applications];

    this.fullName = '';
    this.mobile = '';
    this.pan = '';
    this.email = '';

    this.isSubmitted = false;
  }

  reset(): void {
    // Clear all input fields
    this.fullName = '';
    this.mobile = '';
    this.pan = '';
    this.email = '';

    // Reset validation UI state (hide errors / remove red highlight)
    this.isSubmitted = false;
  }
}
